export const ENV_API_PREFIX = 'API_PREFIX';
export const ENV_SERVER_HOST = 'SERVER_HOST';
export const ENV_SERVER_PORT = 'SERVER_PORT';
export const ENV_CORS_ORIGINS = 'CORS_ORIGINS';
export const ENV_JWT_ACCESS_EXPIRATION_TIME = 'JWT_ACCESS_EXPIRATION_TIME';
export const ENV_JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME';
export const ENV_JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const ENV_JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';


export const ENV_MONGO_URI = 'MONGO_URI';
